#!/bin/bash
# Setup script for CI/CD configuration files
# 
# This script sets up configuration files needed for CI/CD:
# - PHPStan configuration (phpstan.neon)
# - CategoryFactory (if missing)
#
# Note: Test files should be stored directly in backend/tests/Feature/Api/
# and committed to the repository, not generated by this script.

set -e

BACKEND_DIR="backend"
FACTORIES_DIR="$BACKEND_DIR/database/factories"

echo "Setting up CI/CD configuration files..."

# Check if backend directory is writable
TEMP_DIR=""
if [ ! -w "$BACKEND_DIR" ]; then
    echo "Warning: Cannot write to $BACKEND_DIR directory (permission denied)"
    echo "Creating files in temporary location instead..."
    TEMP_DIR="/tmp/hyggestack-setup-$$"
    mkdir -p "$TEMP_DIR/$BACKEND_DIR"
    BACKEND_DIR="$TEMP_DIR/$BACKEND_DIR"
    FACTORIES_DIR="$BACKEND_DIR/database/factories"
    echo "Files will be created in: $TEMP_DIR"
    echo ""
    echo "After fixing permissions, run:"
    echo "  sudo chown -R \$USER:\$USER backend/"
    echo "  cp -r $TEMP_DIR/* ."
    echo "  rm -rf $TEMP_DIR"
    echo ""
fi

# Create PHPStan configuration
if [ ! -f "$BACKEND_DIR/phpstan.neon" ]; then
    cat > "$BACKEND_DIR/phpstan.neon" << 'PHPSTAN_EOF'
includes:
    - vendor/laravel/framework/.phpstan/extension.neon

parameters:
    level: 5
    paths:
        - app
    excludePaths:
        - app/Console/Kernel.php
    checkMissingIterableValueType: false
    checkGenericClassInNonGenericObjectType: false
    ignoreErrors:
        # Laravel specific
        - '#Access to an undefined property [a-zA-Z0-9\\_]+::\$[a-zA-Z0-9_]+#'
        - '#Call to an undefined method [a-zA-Z0-9\\_]+::[a-zA-Z0-9_]+\(\)#'
        # Spatie Permission
        - '#Call to an undefined method Illuminate\\Database\\Eloquent\\Builder::hasRole\(\)#'
        - '#Call to an undefined method Illuminate\\Database\\Eloquent\\Builder::hasAnyRole\(\)#'
        - '#Call to an undefined method Illuminate\\Database\\Eloquent\\Builder::assignRole\(\)#'
        - '#Call to an undefined method Illuminate\\Database\\Eloquent\\Builder::syncRoles\(\)#'
        - '#Call to an undefined method Illuminate\\Database\\Eloquent\\Builder::isAdmin\(\)#'
        - '#Call to an undefined method Illuminate\\Database\\Eloquent\\Builder::isWriter\(\)#'
        # Eloquent dynamic properties
        - '#Access to an undefined property App\\Models\\[a-zA-Z0-9_]+::\$[a-zA-Z0-9_]+#'
PHPSTAN_EOF
    echo "✓ Created phpstan.neon"
else
    echo "✓ phpstan.neon already exists (skipped)"
fi

# Create CategoryFactory if it doesn't exist
if [ ! -f "$FACTORIES_DIR/CategoryFactory.php" ]; then
    # Ensure the factories directory exists
    mkdir -p "$FACTORIES_DIR"
    cat > "$FACTORIES_DIR/CategoryFactory.php" << 'CATEGORYFACTORY_EOF'
<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Models\Category;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Category>
 */
class CategoryFactory extends Factory
{
    protected $model = Category::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $name = fake()->words(2, true);
        
        return [
            'name' => ucwords($name),
            'slug' => \Illuminate\Support\Str::slug($name),
            'description' => fake()->optional()->sentence(),
            'color' => fake()->optional()->hexColor(),
        ];
    }
}
CATEGORYFACTORY_EOF
    echo "✓ Created CategoryFactory.php"
else
    echo "✓ CategoryFactory.php already exists (skipped)"
fi

echo ""
echo "Configuration setup complete!"
if [ -n "$TEMP_DIR" ]; then
    echo ""
    echo "⚠️  Files were created in temporary directory: $TEMP_DIR"
    echo ""
    echo "To complete setup:"
    echo "1. Fix backend directory permissions:"
    echo "   sudo chown -R \$USER:\$USER backend/"
    echo ""
    echo "2. Copy files to their final location:"
    echo "   cp -r $TEMP_DIR/backend/* backend/"
    echo ""
    echo "3. Clean up temporary files:"
    echo "   rm -rf $TEMP_DIR"
    echo ""
else
    echo ""
    echo "Next steps:"
    echo "1. Install PHPStan: cd backend && composer require --dev phpstan/phpstan phpstan/extension-installer"
    echo "2. Run tests: cd backend && php artisan test"
    echo "3. Run PHPStan: cd backend && vendor/bin/phpstan analyse"
fi
